version: '3'

services:
  web:
    build: .
    command:  gunicorn testsite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env.prod

  db:
    image:  postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
       - ./.env.prod.db

volumes:
    postgres_data: